[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://i.ibb.co/.*"]

[build]
  command = "bun install && bun run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
